version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
      - "81:81"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  cypress:
    image: cypress/included:latest
    depends_on:
      - nginx
      - postgres
    environment:
      - CYPRESS_baseUrl=http://nginx:81
    volumes:
      - ./cypress:/e2e
    working_dir: /e2e
    entrypoint: ["sh", "-c", "npm install && ./node_modules/.bin/cypress run"]
